[tools]
delta = "latest"
gh = "latest"
"gitlab:gitlab-org/cli" = "latest"
glow = "latest"
gum = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
"npm:@github/copilot" = "latest"
usage = "latest"
