[tools]
"aqua:delta" = "latest"
"aqua:gh" = "latest"
"gitlab:gitlab-org/cli" = "latest"
"aqua:glow" = "latest"
"core:go" = "latest"
"core:java" = "latest"
"aqua:neovim" = "latest"
"core:node" = "latest"
"npm:@github/copilot" = "latest"
"core:python" = "latest"
"aqua:ttyd" = "latest"
"aqua:usage" = "latest"
"aqua:vhs" = "latest"
