[tools]
"aqua:delta" = "latest"
"aqua:gh" = "latest"
"aqua:neovim" = "latest"
"aqua:ripgrep" = "latest"
"github:github/copilot-cli" = "latest"
"github:anomalyco/opencode" = "latest"
"gitlab:gitlab-org/cli" = "latest"
