[tools]
"core:go" = "latest"
"core:java" = "latest"
"core:node" = "latest"
"core:python" = "latest"
"aqua:delta" = "latest"
"aqua:gh" = "latest"
"aqua:neovim" = "latest"
"aqua:ripgrep" = "latest"
"aqua:ttyd" = "latest"
"aqua:usage" = "latest"
"aqua:vhs" = "latest"
"github:github/copilot-cli" = "latest"
"gitlab:gitlab-org/cli" = "latest"
