[tools]
gh = { version = "latest", os = ["linux"] }
go = { version = "latest", os = ["linux"] }
java = { version = "latest", os = ["linux"] }
lazygit = "latest"
neovim = "latest"
node = { version = "latest", os = ["linux"] }
"npm:@github/copilot" = { version = "latest", os = ["linux"] }
python = { version = "latest", os = ["linux"] }
usage = "latest"

[tasks.list-tool-backends]
description = "Show the backend for each tool managed by mise"
run = "mise ls | awk 'NR>1 {print $1}' | xargs -n1 mise tool | grep '^Backend:'"
