[tools]
gh = "latest"
go = "latest"
java = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
"npm:@github/copilot" = "latest"
python = "latest"
ttyd = "latest"
usage = "latest"
vhs = "latest"

[tasks.list-tool-backends]
description = "Show the backend for each tool managed by mise"
run = '''
mise ls | awk '{print $1}' | xargs -n1 mise tool | grep '^Backend:'
'''
run_windows = '''
mise ls | ForEach-Object { $_.split()[0] } | ForEach-Object { mise tool $_ } | Where-Object { $_ -match '^Backend' }
'''

[settings]
windows_default_inline_shell_args = "powershell -NoProfile -Command"
