[tools]
delta = "latest"
gh = "latest"
glow = "latest"
go = "latest"
java = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
"npm:@github/copilot" = "latest"
python = "latest"
ttyd = "latest"
usage = "latest"
vhs = "latest"
